language: ruby

rvm:
  - 1.9.3
  - 2.0.0

services: 
  - mongodb

before_script:
  - rake db:mongoid:create_indexes

notifications:
  campfire:
    - secure: "eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z\nx2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c\nAyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk="
