before_install: gem update bundler
bundler_args: "--without assets:development:production"
language: ruby
rvm:
- 2.1.1
services:
before_script:
notifications:
  campfire:
    rooms:
    - secure: |-
        eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z
        x2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c
        AyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk=
    on_success: never
    on_failure: always
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/67f80d53-afb0-4344-bd40-2644f55a4462/status
env:
  matrix:
    secure: ZhrMOK9JCzqqiI3mHBNh/g/bUWEZe+SXn91eZuU0zdFKrUlCRwglhABiIf+9a1Ysk1aB0g4LO4tNTV0ku7cdQUHeNabueho88qUKyDj70QB05xHEgtcjelgpD2F9InVi8D47S9UG6LBf9gJAXGN7UTw2CH+sm9q5SLbrKb9fszo=
