---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-demo.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 17 Apr 2014 08:34:05 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - fb2e6b54-acfe-475a-b0df-08afca6a2aa0
      X-Runtime:
      - '0.077409'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 17 Apr 2014 08:34:06 GMT
- request:
    method: get
    uri: http://ohana-api-demo.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 17 Apr 2014 08:50:38 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - ec389ba0-831d-44da-85dc-8e2c5c464bf2
      X-Runtime:
      - '0.059243'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 17 Apr 2014 08:50:39 GMT
recorded_with: VCR 2.8.0
