---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Apr 2014 18:47:57 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&page=0&service_area=&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - abfe95a9-85e0-4470-86ba-b64f7ff22f54
      X-Runtime:
      - '0.061154'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 28 Apr 2014 18:47:57 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&org_name=Custom%20Value&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Apr 2014 18:47:58 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&org_name=Custom+Value&page=0&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 3c210e56-abf1-4e41-bc83-70306c532809
      X-Runtime:
      - '0.041538'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 28 Apr 2014 18:47:58 GMT
recorded_with: VCR 2.9.0
