---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Apr 2014 18:47:31 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&page=0&service_area=&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - b88560bd-befa-4c32-a01d-65a803406be8
      X-Runtime:
      - '0.121032'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 28 Apr 2014 18:47:31 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=Custom%20Value&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Apr 2014 18:47:32 GMT
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 400 Bad Request
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 7d2fc1f5-52df-4552-b5ae-9d09399ae3ca
      X-Runtime:
      - '0.157876'
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Mon, 28 Apr 2014 18:47:32 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Apr 2014 18:47:32 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg&page=0>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 0af0c4bc-9942-4344-ba48-77d8708a9620
      X-Runtime:
      - '0.064302'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 28 Apr 2014 18:47:32 GMT
recorded_with: VCR 2.9.0
