---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&location=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:27 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?keyword=asdfg&location=&page=0&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - 6e3732b2-f98c-4cc2-b532-c098d18389f1
      X-Runtime:
      - '0.016068'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '34'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:27 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&location=94403&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:28 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?location=94403&page=6&utf8=%E2%9C%93>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?location=94403&page=2&utf8=%E2%9C%93>;
        rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - 7289d32e-1775-42c5-ad0f-156b15260b65
      X-Runtime:
      - '0.248534'
      X-Total-Count:
      - '6'
      X-Total-Pages:
      - '6'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '559'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":19,"admin_emails":[],"coordinates":[-122.2931236,37.5326941],"description":"Provides
        free medical and dental care to those in need. Offers basic medical care for
        adults.","latitude":37.5326941,"longitude":-122.2931236,"name":"San Mateo
        Free Medical Clinic","short_desc":"Provides free medical and dental care to
        those in need. Offers basic medical care for adults.","slug":"san-mateo-free-medical-clinic","updated_at":"2014-07-15T13:20:13.307-07:00","urls":["http://www.samaritanhouse.com"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/san-mateo-free-medical-clinic/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/san-mateo-free-medical-clinic/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/san-mateo-free-medical-clinic/services","url":"http://ohana-api-test.herokuapp.com/api/locations/san-mateo-free-medical-clinic","address":{"id":19,"street":"19
        West 39th Avenue","city":"San Mateo","state":"CA","zip":"94403"},"organization":{"id":5,"name":"Samaritan
        House","slug":"samaritan-house","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/samaritan-house","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/samaritan-house/locations"},"phones":[{"id":19,"department":null,"extension":null,"number":"650
        578-0400","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:28 GMT
recorded_with: VCR 2.9.2
