---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&keyword=asdfg&location=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:29 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?keyword=asdfg&location=&page=0&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - ccd5da9b-690e-45d9-9f72-0534f885c6dd
      X-Runtime:
      - '0.016951'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '34'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:29 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:29 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?page=24&utf8=%E2%9C%93>; rel="last",
        <http://ohana-api-test.herokuapp.com/api/search?page=2&utf8=%E2%9C%93>; rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - 94bfd9c3-3332-4128-afbc-34bd2f9d3c65
      X-Runtime:
      - '0.042587'
      X-Total-Count:
      - '24'
      X-Total-Pages:
      - '24'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '1255'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":1,"admin_emails":[],"coordinates":[-122.213221,37.477227],"description":"A
        walk-in center for older adults that provides social services, wellness, recreational,
        educational and creative activities including arts and crafts, computer classes
        and gardening classes. Coffee and healthy breakfasts are available daily.
        A hot lunch is served Tuesday-Friday for persons age 60 or over and spouse.        Provides
        case management (including in-home assessments) and bilingual information
        and referral about community services to persons age 60 or over on questions
        of housing, employment, household help, recreation and social activities,
        home delivered meals, health and counseling services and services to shut-ins.
        Health insurance and legal counseling is available by appointment. Lectures
        on a variety of health and fitness topics are held monthly in both English
        and Spanish.  Provides a variety of physical fitness opportunities, including
        a garden club, yoga, tai chi, soul line dance and aerobics classes geared
        toward older adults. Also provides free monthly blood pressure screenings,
        quarterly blood glucose monitoring and health screenings by a visiting nurse.
        Offers a Brown Bag Program in which low-income seniors can receive a bag of
        groceries each week for a membership fee of $10 a year. Offers Spanish lessons.
        Formerly known as Peninsula Family Service, Fair Oaks Intergenerational Center.
        Formerly known as the Fair Oaks Senior Center. Formerly known as Family Service
        Agency of San Mateo County, Fair Oaks Intergenerational Center.","latitude":37.477227,"longitude":-122.213221,"name":"Fair
        Oaks Adult Activity Center","short_desc":"A multipurpose senior citizens''
        center serving the Redwood City area.","slug":"fair-oaks-adult-activity-center","updated_at":"2014-05-09T20:49:18.836-07:00","urls":["http://www.peninsulafamilyservice.org"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center/services","url":"http://ohana-api-test.herokuapp.com/api/locations/fair-oaks-adult-activity-center","address":{"id":1,"street":"2600
        Middlefield Road","city":"Redwood City","state":"CA","zip":"94063"},"organization":{"id":1,"name":"Peninsula
        Family Service","slug":"peninsula-family-service","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/peninsula-family-service/locations"},"phones":[{"id":1,"department":null,"extension":null,"number":"650
        780-7525","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:30 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&controller=organizations&location=Redwood%20City,%20CA&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.1.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 16 Jul 2014 08:16:30 GMT
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?location=Redwood+City%2C+CA&page=12&utf8=%E2%9C%93>;
        rel="last", <http://ohana-api-test.herokuapp.com/api/search?location=Redwood+City%2C+CA&page=2&utf8=%E2%9C%93>;
        rel="next"
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.45
      Status:
      - 200 OK
      X-Content-Type-Options:
      - nosniff
      X-Current-Page:
      - '1'
      X-Frame-Options:
      - SAMEORIGIN
      X-Next-Page:
      - '2'
      X-Powered-By:
      - Phusion Passenger 4.0.45
      X-Request-Id:
      - 234fa99c-b7e2-4de8-9ae5-237fb88b77d7
      X-Runtime:
      - '0.238656'
      X-Total-Count:
      - '12'
      X-Total-Pages:
      - '12'
      X-Xss-Protection:
      - 1; mode=block
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[{"id":10,"admin_emails":[],"coordinates":[-122.227409,37.4837662],"description":"Provides
        general reading and media materials, literacy and homework assistance, and
        programs for all ages. Provides public computers, wireless connectivity, a
        children''s room, teen center, and a local history collection. The library
        is a member of the Peninsula Library System. The Fair Oaks Branch (650-780-7261)
        is located at 2510 Middlefield Road and is open Monday-Thursday, 10-7; Friday,
        10-5. The Schaberg Branch (650-780-7010) is located at 2140 Euclid Avenue
        and is open Tuesday-Thursday, 1-6; Saturday, 10-3. The Redwood Shores Branch
        (650-780-5740) is located at 399 Marine Parkway and is open Monday-Thursday,
        10-8; Saturday, 10-5; Sunday 12-5.","latitude":37.4837662,"longitude":-122.227409,"name":"Main
        Library","short_desc":"Provides general reference and reading materials to
        adults, teenagers and children.","slug":"main-library","updated_at":"2014-05-09T20:49:18.920-07:00","urls":["http://www.redwoodcity.org/library"],"contacts_url":"http://ohana-api-test.herokuapp.com/api/locations/main-library/contacts","faxes_url":"http://ohana-api-test.herokuapp.com/api/locations/main-library/faxes","services_url":"http://ohana-api-test.herokuapp.com/api/locations/main-library/services","url":"http://ohana-api-test.herokuapp.com/api/locations/main-library","address":{"id":10,"street":"1044
        Middlefield Road","city":"Redwood City","state":"CA","zip":"94063"},"organization":{"id":3,"name":"Redwood
        City Public Library","slug":"redwood-city-public-library","urls":[],"url":"http://ohana-api-test.herokuapp.com/api/organizations/redwood-city-public-library","locations_url":"http://ohana-api-test.herokuapp.com/api/organizations/redwood-city-public-library/locations"},"phones":[{"id":10,"department":"Circulation","extension":null,"number":"650
        780-7018","number_type":null,"vanity_number":null}]}]'
    http_version: 
  recorded_at: Wed, 16 Jul 2014 08:16:30 GMT
recorded_with: VCR 2.9.2
