---
http_interactions:
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - <API_TOKEN>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 03 Mar 2014 05:52:35 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Server:
      - nginx/1.4.4 + Phusion Passenger 4.0.37
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Powered-By:
      - Phusion Passenger 4.0.37
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 19e0213f-66c4-481f-a5ba-76f07a27bf5a
      X-Runtime:
      - '0.039885'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[]'
    http_version: 
  recorded_at: Mon, 03 Mar 2014 05:52:35 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - <API_TOKEN>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Mon, 03 Mar 2014 07:17:25 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Server:
      - nginx/1.4.4 + Phusion Passenger 4.0.37
      Status:
      - 200 OK
      X-Current-Page:
      - '1'
      X-Powered-By:
      - Phusion Passenger 4.0.37
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 0bfcdf68-7a1e-4abf-bb70-15b7ad3e4b94
      X-Runtime:
      - '0.029139'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '[]'
    http_version: 
  recorded_at: Mon, 03 Mar 2014 07:17:25 GMT
recorded_with: VCR 2.8.0
