---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:39 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&page=0&service_area=&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 3317d5e8-cf73-4fd5-b87f-85380a91084a
      X-Runtime:
      - '0.015836'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:38 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Apr 2014 06:29:40 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&page=0&service_area=smc&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 447be742-e8ec-4a90-8a4f-7f4deb8324fa
      X-Runtime:
      - '0.021008'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Tue, 29 Apr 2014 06:29:39 GMT
recorded_with: VCR 2.9.0
