---
http_interactions:
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Fri, 09 May 2014 22:24:03 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=&page=0&service_area=&utf8=%E2%9C%93>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - c8d43187-cf40-4734-97f1-3c1aaa1b7234
      X-Runtime:
      - '0.023333'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Fri, 09 May 2014 22:24:03 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&location=Custom%20Value&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Fri, 09 May 2014 22:24:04 GMT
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 400 Bad Request
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - ce4863f3-6989-4c1c-aa89-e51eed13df41
      X-Runtime:
      - '0.053704'
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Fri, 09 May 2014 22:24:04 GMT
- request:
    method: get
    uri: http://ohana-api-test.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Fri, 09 May 2014 22:24:04 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Link:
      - <http://ohana-api-test.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg&page=0>;
        rel="last"
      Server:
      - nginx/1.4.7 + Phusion Passenger 4.0.40
      Status:
      - 200 OK
      X-Powered-By:
      - Phusion Passenger 4.0.40
      X-Request-Id:
      - 3e4630cc-e3b8-4bef-a39f-21957f16c28a
      X-Runtime:
      - '0.023989'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Fri, 09 May 2014 22:24:04 GMT
recorded_with: VCR 2.9.0
