files: ["app/**/*.js"] # No need to put app/assets/ or vendor/assets here
options:
  boss:       true
  browser:    true
  curly:      false
  eqeqeq:     true
  eqnull:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     true
  noarg:      true
  sub:        true
  trailing:   true
  undef:      true
  unused:     false
  globals:
    "console"   : false
    "require"   : false
    "define"    : false
    "Modernizr" : false
    "selectorSupported" : false
    "google"    : false
