paths:
  enquire: 'enquire.min'
  domReady: 'requirejs/domReady'
  async: 'requirejs/async'
  classList: 'remy-polyfills/classList'

modules:
  - name: 'routes/home/index'
  - name: 'routes/about/index'
  - name: 'routes/organizations/index'
  - name: 'routes/organizations/show'